export const GET_CRYPTO_SUCCESS = "GET_CRYPTO_SUCCESS";
export const GET_CRYPTO_ERROR = "GET_CRYPTO_ERROR";
export const GET_CRYPTO_LOADING = "GET_CRYPTO_LOADING";
export const CONNECTION_STATUS_CHANGE = "CONNECTION_STATUS_CHANGE";