export const GET_CRYPTO_DETAILS_SUCCESS = "GET_CRYPTO_DETAILS_SUCCESS";
export const GET_CRYPTO_DETAILS_ERROR = "GET_CRYPTO_DETAILS_ERROR";
export const GET_CRYPTO_DETAILS_LOADING = "GET_CRYPTO_DETAILS_LOADING";
export const GET_GRAPH_DATA_SUCCESS = "GET_GRAPH_DATA_SUCCESS";
export const GET_GRAPH_DATA_LOADING = "GET_GRAPH_DATA_LOADING";
export const GET_GRAPH_DATA_ERROR = "GET_GRAPH_DATA_ERROR";